json-database:
  file-name: database.json

json-index:
  file-name: index.json

xkcd-com:
  url: https://xkcd.com
  language: en
  batch-size: 50
  number-of-workers: 50
  timeout: 5s

http-server:
  host: localhost
  port: 8080
  comix-update-interval: 1d