xkcd-com:
  url: https://xkcd.com
  language: en
  batch-size: 50
  number-of-workers: 50
  timeout: 5s

http-server:
  host: localhost
  port: 8080
  comix-update-interval: 24h

postgres:
  dsn: postgres://user:password@localhost:5432/goxkcd?sslmode=disable
  migrations-path: ./internal/infrastructure/postgres/migrations
